#+title: Borth Core Implementation
#+PROPERTY: header-args :tangle borth-core.js
* Core
** General Structure
All words in the system are functions that take a runtime context, and return a runtime context.

The runtime context contains:
- the input buffer (for parsing words)
- a data stack
- a compilation-unit stack
- a dictionary of all vocabularies in the system

** Misc / Utils
Random things that don't warrant their own top level section.
*** Gensym
Symbol generation so even anonymous things can be proper words in a vocab
#+begin_src js
let _gensymCount = 0
export const gensym = (name = 'GENERATED') => `'@@GENSYM'__${name}__${_gensymCount++}`
#+end_src
*** Tracing
#+begin_src js :tangle no
const tracing = {
  active: true,
  log(...args) {
    this.active && console.log(...args)
  },
  warn(...args) {
    this.active && console.warn(...args)
  }
}
#+end_src
*** Constants / Predicates
The only constants we need to formally specify in the implementation are what the whitespace seperators are.
#+begin_src js
export const WS = ' \t\n\r';
export const isWS = c => WS.includes(c)
#+end_src
*** Errors / Assertions
Useful little errors and things so I don't have ugly if statements and throw statements.
#+begin_src js
export const panic = (msg, label = 'panic') => {
  throw new Error(`${label}: ${msg}`)
}
export const assert = (cond, msg) => cond || panic(`Assertion failed! ${msg}`, 'assert')
#+end_src
*** multiple arity fns
#+begin_src js
export const nary = (...fns) => {
  const impls = fns.reduce((acc, f) => ({...acc, [f.length]: f}), {});
  return (...args) => {
    const impl = impls[args.length]
    if(!impl) panic(`no implemented for ${args.length} arguments!`)
    return impl(...args)
  }
}
#+end_src
*** castArr
#+begin_src js
export const castArr = v => {
  if (Array.isArray(v)) return v
  if (v === undefined || v === null) return []
  return [v]
}
#+end_src

** Context Access
*** Stack Manipulation
#+begin_src js
const take = (arr, n) => arr.splice(arr.length - n, n)
const append (arr, items) => arr.splice(arr.length, 0, ...items)
#+end_src

*** Tokenization
#+begin_src js
export const nextToken = ctx => {
  const lastPos = ctx.pos ?? 0
  while (ctx.pos < ctx.src.length && isWS(ctx.src[ctx.pos])) ctx.pos++
  if (ctx.pos >= ctx.src.length) return undefined
  const start = ctx.pos
  while (ctx.pos < ctx.src.length && !isWS(ctx.src[ctx.pos])) ctx.pos++
  ctx.lastPos = lastPos
  return ctx.src.slice(start, ctx.pos)
}
export const nextTokens = (ctx, n) => {
  const out = []
  for (let i = 0; i < n; i++) out.push(nextToken(ctx))
  return out
}
export const parseUntil = (ctx, stopToken) => {
  // skip the trailing space of the start token
  const start = ctx.pos + 1
  let next
  while ((next = nextToken(ctx))) {
    if (next === stopToken) {
      // stop 1 char earlier because of trailing space for tokens
      const stop = ctx.pos - stopToken.length - 1
      return ctx.src.slice(start, stop)
    }
  }
  panic(`unmatched delimiter starting beginning at pos: ${start} expected: ${stopToken}`)
}
#+end_src
*** Staged Compilation
#+begin_src js
export const currentScope = (ctx) => ctx.scope.at(-1);
export const stage = (ctx, ...items) => {
  const current = currentScope(ctx);
  current.staging.push(...items)
  return ctx
}
export const enterCompilationScope = (ctx, onExit) => {
  const scope = {
    staging: [],
    onExit,
  }
  ctx.scope.push(scope)
  return ctx
}
export const exitCompilationScope = async (ctx) => {
  const {onExit, ...scope} = ctx.scope.pop()
  scope.stopPos = ctx.pos;
  const definition = ctx.src.slice(scope.startPos, scope.stopPos);
  await ctx.emit({definition});
  assert(scope, `failed to exit compilation scope`)
  const current = currentScope(ctx);
  const toStage = castArr(await onExit(ctx, scope))
  if(current) {
    await stage(ctx, ...toStage)
  }
  return toStage
}
#+end_src
*** Word Resolution
Words resolution simply takes a word name, and attempts to return the defined word.
If it is not found:
- We check if the word is a valid number
- If it is, we return the number
- Otherwise we throw an error

  #+begin_src js
export const find = (ctx, name) => {
  if (ctx.ns.has(name)) return ctx.ns.get(name)
  for (const ns of ctx.search) {
    if(ns.has(name)) return ns.get(name)
  }
  const num = Number(name)
  if (!isNaN(num)) return constant(num)
  panic(`unknown: ${name}`)
}
export const define = (ctx, word) => {
  if (!word.props.name) {
    word.props.name = gensym()
  }
  if(ctx.ns.has(name)) {
    const w = ctx.ns.get(name);
    w.impl = word.impl;
    w.props = word.props
    return w
  } else {
    ctx.ns.set(name, word)
    return word
  }
}
  #+end_src
**** Old
#+begin_src js :tangle no
export const find = (ctx, name) => {
  if (ctx.ns.has(name)) return ctx.ns.get(name)
  for (const ns of ctx.search) {
    if(ns.has(name)) return ns.get(name)
  }
  const num = Number(name)
  if (!isNaN(num)) return constant(num)
  panic(`unknown: ${name}`)
}
export const define = (ctx, word) => {
  let name = props(word).name
  if (!name) {
    name = gensym()
    props(word, { name })
  }
  let defined;
  if(ctx.ns.has(name)) {
    const w = ctx.ns.get(name);
    impl(w, word.impl)
    w.props = word.props
    defined = w
  } else {
    ctx.ns.set(name, word)
    defined = word
  }
  return defined
}
#+end_src
** Words
These just make host language words easier to write.
*** word, makes a word
Words are functions of the form: =ctx -> ctx=.
We can make new words using =word(fn)= or =word(fn, props)= to include default properties.

Word functions have two additional properties:
- =.impl=
  The implementation of the words behavior
  Access using =impl(word)=, update using =impl(word, fn)=

- =.props=
  An object representing the words properties.
  Access using =props(word)=
  Update using =props(word, anObject)=
  Replace using =props(word, aReplacementFn)=

  #+begin_src js
export const word = (fn, props = {}) => ({
  props,
  impl: fn ?? () => panic("No implemented!"),
  async exec() {
    return this.impl(await ctx)
  }
})
  #+end_src

**** old
#+begin_src js :tangle no
export const word = nary(
  () => word((_ctx) => panic('No implementation!'), {}),
  (fn) => word(fn, {}),
  (fn, props) => ({
    props,
    impl: fn,
    async exec(ctx) {
      return this.impl.call(this, await ctx)
    },
  })
)
export const impl = nary(
  word => word.impl ?? panic(`No impl on: ${word}`),
  (word, fn) => (word.impl = fn, word)
)
export const props = nary(
  word => word.props ?? panic(`No properties on: ${word}`),
  (word, obj) => {
    if(typeof obj === 'function') {
      const f = obj;
      word.props = {...f(word.props)};
    } else {
      word.props = {...word.props, ...obj};
    }
    return word
  }
)
#+end_src
*** stackify, helper for easy stack fns
Stackify wraps a function and makes it work naturally with the stack.

This returns a word implementation function, =ctx -> ctx=.

It will:
+ Bind arguments from lowest to highest from the stack
  So for a function with 2 args =(a, b)=, and a stack =[1, 2, 3]=:
  + a is 2
  + b is 3
+ Append the result to the stack
   It will coerce the result to an array, and append this array to the stack.
   To return an array as a single value, wrap it in an array.

This makes the args and outputs have the same "orientation".
=(deepest, highest) -> [deepest, highest]=

Note:
+ It will throw a stack underflow error if there are not enough items on the stack.
+ It filters undefined elements of the result array before appending
  Use null or false when representing missing values

#+begin_src js
export const stackify = fn => async ctx => {
  const args = await pop(ctx, fn.length)
  const result = castArr(await fn(...args)).filter(v => v !== undefined)
  return push(ctx, ...result)
}
#+end_src

*** Useful word factories
#+begin_src js
export const variable = (initial, extraProps) => word(
    stackify(() => [props(this).slot]),
    { type: 'variable', slot: initial, ...extraProps }
  )
export const def = (fn, extraProps) => word(stackify(fn), { type: 'primitive', ...extraProps })
export const syn = (fn, extraProps) => word(fn, { type: 'syntax', parsing: true, ...extraProps })
export const constant = (value, e) => def(() => [value], {type: 'constant', value, ...e})
#+end_src

** Compilation
*** How compilation works
In our system we perform compilation with words that push a new compilation unit onto the compilation-unit stack, similar to Factor.

These words are special because when used inside of a compilation-unit (as we do when compiling some source), they don't append a reference to their word, instead they evaluate immediately. We call these words parsing words, since they evaluate at parse time.

So if a word normally evaluates at phase n, parsing words evaluate at phase n-1.

Different parsing words will modify compilation units differently. Parsing words such as =;= are delimiters, which just means they exit the current compilation context word, which will commit the accumulated staging words.

So in short, compilation is a function of the form =compile(ctx, source) -> quotation=

#+begin_src js
export const compile = async (ctx, source) => {
  let compCtx = { ...ctx, src: source, lastPos: 0, pos: 0, stack: undefined }
  enterCompilationScope(compCtx, (ctx, {staging}) => staging);
  let name;
  while ((name = nextToken(compCtx)) !== undefined) {
    const word = find(compCtx, name)
    const { parsing } = props(word)
    if (parsing) {
      compCtx = await word.exec(compCtx)
    } else {
      await stage(compCtx, word);
    }
  }
  return exitCompilationScope(compCtx);
}

export const evaluate = async (ctx, compiled) => {
  for (const w of compiled) {
    ctx = await w.exec(await ctx)
  }
}

export const run = async(ctx, source) => {
  const compiled = await compile(ctx, source);
  await evaluate(ctx, compiled);
  return ctx
}
#+end_src

** Context Creation
#+begin_src js
export const docol = (name, words, additionalProps) => {
  const w = word(
    //async c => (await evaluate(c, props(w).words), c),
    async c => (await evaluate(c, words), c),
    { type: 'compiled', name, words, ...additionalProps }
  );
  return w
}
export const freshContext = () => {
  const scratch = new Map();
  const ctx = {
    ns: scratch,
    emit: console.log,
    vocabs: {scratch},
    search: [],
    stack: [],
    scope: []
  }
  return ctx
}
#+end_src

* Playground
#+begin_src js :tangle no
const c = freshContext()

const colonDef = syn(c => {
  const start = c.lastPos;
  const name = nextToken(c)
  enterCompilationScope(c, async (ctx, {staging}) => {
    // with definitions, we don't stage anything
    await define(ctx, await docol(name, staging));
  });
  currentScope(c).startPos = start
  return c
})
const syntaxDef = syn(c => {
  const start = c.pos;
  const name = nextToken(c)
  enterCompilationScope(c, async (ctx, {staging}) => {
    // with definitions, we don't stage anything
    await define(ctx, await docol(name, staging, {parsing: true}));
  });
  currentScope(c).startPos = start
  return c
});
const delim = syn(async c => {
  await exitCompilationScope(c)
  return c;
})

const scratch = new Map()
scratch.set(':', colonDef)
scratch.set('syn:', syntaxDef)
scratch.set(';', delim)
scratch.set('parse:', syn(async c => {
  const name = nextToken(c);
  const delimiter = nextToken(c);
  const parserWord = syn(async c => {
    const parsed = parseUntil(c, delimiter);
    stage(c, constant(parsed))
    return c
  })
  props(parserWord, {name})
  define(c, parserWord)
  return c
}))
scratch.set('\\', syn(c => {
  const name = nextToken(c);
  const w = find(c, name);
  stage(c, constant(w))
  return c
}))
scratch.set('+', def((a, b) => [a + b]))
scratch.set('.', word(async c => {
  const [a] = pop(c, 1)
  await c.emit({log: a})
  return c
}, {type: 'primitive'}))

c.ns = scratch
c.vocabs['scratch'] = scratch

const s = `
  parse: << >>

  : bar << hello there this is a test of custom parsing >> ;
  : baz 20 ;
  : foo baz baz ;

  : literally-foo \\ foo ;

  foo + .
  bar .

  literally-foo .
`

console.log("before evaluation: ", c.stack)
const comp = await compile(c, s)

await evaluate(c, comp)
console.log("after evaluation: ", c.stack)

console.log('recompiling')
await run(c, ': foo 420 100 ; ')

await evaluate(c, comp)
console.log("evaluation after recompiling", c.stack)
#+end_src

#+RESULTS:
