packages:
  #- apps/visual
  #- apps/diagram
  #- apps/brain
  - apps/daemon
  - packages/brain
  - packages/core
  - packages/ontology
  - packages/crypto
  - packages/react
  - packages/std

onlyBuiltDependencies:
  - esbuild
  - electron
