// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bassline-playground": {
    params: {};
  };
  "/playground": {
    params: {};
  };
  "/sugar-demo": {
    params: {};
  };
  "/canvas-v2": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/bassline-playground" | "/playground" | "/sugar-demo" | "/canvas-v2" | "/home";
  };
  "routes/bassline-playground.tsx": {
    id: "routes/bassline-playground";
    page: "/bassline-playground";
  };
  "routes/playground.tsx": {
    id: "routes/playground";
    page: "/playground";
  };
  "routes/sugar-demo.tsx": {
    id: "routes/sugar-demo";
    page: "/sugar-demo";
  };
  "routes/canvas-v2.tsx": {
    id: "routes/canvas-v2";
    page: "/canvas-v2";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};