// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/spreadsheet": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/repl": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/spreadsheet" | "/home" | "/repl";
  };
  "routes/spreadsheet.tsx": {
    id: "routes/spreadsheet";
    page: "/spreadsheet";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/repl/route.tsx": {
    id: "routes/repl";
    page: "/repl";
  };
};