// Portable core — no Node.js imports
export { Platform, platform, Resource, kResource, ResourceMirror, connect } from './kernel/platform.js'
export { Grammar, ComposedGrammar, DoesNotUnderstandError, fallback, broadcast } from './kernel/grammar.js'
export { EventBusGrammar, EventBus } from './resources/eventbus.js'
export { SlotGrammar, Slot, Max, Min, Union } from './resources/reducers.js'
export { ScopeGrammar, ExtendedScopeGrammar, Scope } from './resources/scope.js'
export { Propagator } from './resources/propagators.js'
export { GatedScope } from './resources/gate.js'
export { PersistentSlot, PersistentScope, memoryStorage } from './resources/persistence.js'
export { default as reducers } from './resources/reducers.js'
export { default as scope } from './resources/scope.js'
export { default as propagators } from './resources/propagators.js'
export { default as garage, Garage } from './infra/garage.js'
export { default as link, memoryTransport } from './link/runtime.js'
export { default as client, ManagedConnection } from './link/client.js'
export { default as gate } from './resources/gate.js'
export { default as persistence } from './resources/persistence.js'
